server:
  port: 8080
spring:
  application:
    name: "@pom.artifactId@"
  config:
    import: 'file:etc/app.properties'
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
---
spring:
  config:
    activate:
      on-profile: prod
  activemq:
    broker-url: tcp://localhost:61616
    password: ${activemq.password:admin}
    user: admin
